
import static spark.Spark.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {


    public static void main(String[] args) {

        get("/hello", (req, res) -> "Hello World");

    }
}
